import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title:
    "MuntaMart Bangladesh - Shop for handmade, vintage, custom, and unique gifts for everyone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background text-foreground antialiased font-normal text-sm",
          inter.className,
          lora.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
